# Generated by Django 5.2.17 on 2026-09-21 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('max_pets', models.PositiveIntegerField(default=10)),
                ('max_appointments_month', models.PositiveIntegerField(default=20)),
                ('max_products', models.PositiveIntegerField(default=20)),
                ('max_ai_predictions_month', models.PositiveIntegerField(default=0)),
                ('has_ai_churn', models.BooleanField(default=False)),
                ('has_ai_forecast', models.BooleanField(default=False)),
                ('has_reports', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('has_custom_domain', models.BooleanField(default=False)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['order', 'price_monthly'],
            },
        ),
    ]
