# Generated by Django 5.2.17 on 2026-09-20 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('archived', 'Arquivado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_ml_models',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probability', models.FloatField()),
                ('features_used', models.JSONField(blank=True, default=dict)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='owners.owner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='tenants.tenant')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ai.mlmodel')),
            ],
            options={
                'db_table': 'ai_churn_predictions',
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['tenant', 'probability'], name='ai_churn_pr_tenant__7d518f_idx'), models.Index(fields=['tenant', 'predicted_at'], name='ai_churn_pr_tenant__2fdbc2_idx')],
            },
        ),
    ]
