# Generated by Django 5.2.17 on 2026-09-20 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('blocked', 'Bloqueado')], default='active', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='tenants.tenant')),
            ],
            options={
                'db_table': 'owners',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['tenant', 'full_name'], name='owners_tenant__5c23a1_idx'), models.Index(fields=['tenant', 'email'], name='owners_tenant__885a4d_idx'), models.Index(fields=['tenant', 'status'], name='owners_tenant__655917_idx')],
            },
        ),
    ]
