# Generated by Django 5.2.17 on 2026-09-20 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('DOG', 'Cão'), ('CAT', 'Gato'), ('BIRD', 'Ave'), ('OTHER', 'Outro')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Macho'), ('FEMALE', 'Fêmea')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('microchip', models.CharField(blank=True, default='', max_length=100)),
                ('neutered', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='owners.owner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'name'], name='pets_tenant__416b01_idx'), models.Index(fields=['tenant', 'species'], name='pets_tenant__15135b_idx'), models.Index(fields=['tenant', 'owner'], name='pets_tenant__3d34dd_idx'), models.Index(fields=['tenant', 'is_active'], name='pets_tenant__731bfd_idx')],
            },
        ),
    ]
