# Generated by Django 6.0.5 on 2026-06-17 00:12

import apps.pets.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'owners',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.pets.models.pet_photo_path)),
                ('is_active', models.BooleanField(default=True)),
                ('microchip', models.CharField(blank=True, default='', max_length=100)),
                ('neutered', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.owner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['tenant'], name='owners_tenant__6154c7_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['tenant', 'full_name'], name='owners_tenant__5c23a1_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['tenant', 'email'], name='owners_tenant__885a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['tenant', 'cpf'], name='owners_tenant__04d83d_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['tenant', 'phone'], name='owners_tenant__b76a03_idx'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('tenant', 'cpf'), name='unique_owner_cpf_tenant'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('tenant', 'email'), name='unique_owner_email_tenant'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='pets_owner_i_3d9684_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tenant', 'name'], name='pets_tenant__416b01_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tenant', 'species'], name='pets_tenant__15135b_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['is_active'], name='pets_is_acti_5f20c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tenant', 'owner'], name='pets_tenant__3d34dd_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tenant', 'microchip'], name='pets_tenant__e4d273_idx'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(condition=models.Q(('microchip', ''), _negated=True), fields=('tenant', 'microchip'), name='unique_pet_microchip_tenant'),
        ),
    ]
